lexer.*=null # Disable lexer (syntax highlighting)

# Detect line endings and indentation
eol.auto=1
indent.auto=1

fold=0 # Dont fold
fold.margin.width=0 # Dont display fold margin

braces.check=0 # Dont highlight matching braces
braces.sloppy=0 # ????

virtual.space=2 # Put cursor anywhere

strip.trailing.spaces=1

style.*.32=font:Liberation Mono,size:12,fore:#000000,back:#FCFEE9

statusbar.visible=1
statusbar.number=1
statusbar.text.1=    $(LineNumber):$(ColumnNumber) $(OverType)  $(ReadOnly)  BufLen=$(BufferLength)  NbOfLines=$(NbOfLines)  EOLMode=$(EOLMode)    $(FilePath)

view.indentation.guides=0