[font]
normal      = { family = "Fira Code", style = "Normal" }
bold        = { family = "Fira Code", style = "Bold" }
italic      = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 16

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[window]
dynamic_padding = true
startup_mode = "Maximized"
