#!/bin/bash

SEARCH_TARGET="nocheckin"
CASE_INSENSITIVE=true

staged_files=$(git diff --name-only --cached --diff-filter=d)

GREP_OPTS="-n"
if [ "$CASE_INSENSITIVE" = true ]; then
  GREP_OPTS="$GREP_OPTS -i"
fi

exit_code=0

for staged_file in ${staged_files}; do
  if git grep ${GREP_OPTS} ${SEARCH_TARGET} :$staged_file; then
    exit_code=1
  fi
done

CL_BRED='\033[1;31m'
CL_NONE='\033[0m'
if [ "$exit_code" -ne 0 ]; then
  echo -e "${CL_BRED}Aborting!${CL_NONE} $SEARCH_TARGET(s) found in staged files."
fi

exit $exit_code
